name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  EM_VERSION: 3.1.25
  EM_CACHE_FOLDER: 'emsdk-cache'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ci_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: sudo apt-get -y install cmake libx11-dev libxext-dev libxfixes-dev libxi-dev libxcursor-dev libgl1-mesa-dev libglfw3-dev libasound2-dev
      - uses: actions/checkout@v3
      - name: Build Ubuntu
        run: make
